defmodule Scoria.Observe.Guardrail do
  @moduledoc """
  Makes guardrails first-class (D-05a). A guardrail is a **policy decision
  point** Scoria evaluates on the runtime path of an AI step, whose outcome
  can **allow**, **block**, or **escalate** that step to a human. This is
  not invented vocabulary -- it describes code that already exists, using
  verbs already in the source (`ReleaseGate.check/1`,
  `Verdict.blocks_release?/1`). Nouns: gate, policy, decision, reason code,
  subject. Verbs: check, allow, block, escalate.

  **The differentiator, stated plainly: every peer models the *check*;
  almost none model the *decision*.** OpenInference's `GUARDRAIL` span kind
  has zero outcome attributes. Langfuse's `GUARDRAIL` observation type has
  no effect field. OTel explicitly rejected a GenAI policy vocabulary and
  routed it to a generic namespace that still has no outcome field. The
  missing primitive across the whole ecosystem is `effect` -- and XACML has
  had it since 2013. This module's `decision` attribute (see
  `Semconv.guardrail_keys/0`) is that primitive.

  **Vocabulary divergence to flag for Phase 54:** OpenInference defines
  `GUARDRAIL` narrowly (protecting against jailbreak prompts). Scoria's
  definition is BROADER -- any runtime policy gate. Defensible, but say so,
  or an adopter will assume it means content moderation.

  **`"modify"` is RESERVED (D-05h)** as a future XACML *obligation*: a
  future `modify` decision would carry an obligation the caller MUST
  discharge or deny -- a fail-closed contract, not a suggestion. The
  DECISION (allow/block/escalate) stays separate from the REMEDIATION (what
  the caller does about it); Guardrails AI's failure-action taxonomy keeps
  these deliberately separate, and a future PR must not collapse them.
  `Semconv.guardrail_decisions/0` does not include `"modify"`.

  **`not_applicable` produces NO span (D-05d).** XACML's `NotApplicable`.
  Corollary worth recording: today nothing can distinguish a *passed* gate
  from a *skipped* one -- Pundit and CanCanCan both needed bolt-on
  authorization-verification safety nets for exactly this reason. A
  decision record makes "was this checked?" observable by construction.

  **There is no free-text reason key, and there will not be one (SEC-01,
  the sharpest rule in the phase).** Every masking layer in the ecosystem
  (Langfuse, LangSmith, Traceloop) targets model inputs and outputs; none
  catches a guardrail's own free-text explanation -- which is generated by
  a model that just read the PII and routinely quotes it verbatim.
  `Scoria.Eval.JudgeRunner` produces exactly that shape (a free-form
  `explanation:` at `judge_runner.ex:167`/`:202`) and is one refactor away
  from this seam. `emit/1` is structurally immune: it projects its input
  through `Semconv.guardrail_attributes/1`, a FIXED five-key projector that
  never spreads its input map. A caller who passes a `reason:` or an
  `explanation:` key gets it silently ignored, because the projector does
  not read keys it does not own -- this is a structural guarantee, not a
  review convention.

  **The known gap (D-08):** a fired guardrail lands in Postgres and NO
  OPERATOR CAN SEE THE EVENT in v3.6. The span this module emits is
  visible; the point-event (`guardrail_triggered`) is Phase 53b and its
  operator UI is a roadmapped follow-on. This is a deliberate, known gap --
  not a silent omission.

  ## API shape (resolves RESEARCH's Open Question 1)

  Two shapes exist and they serve different callers:

  - `Scoria.Observe.with_guardrail/3` (plan 53-03) -- the generic timing
    wrapper for a HOST that wants to wrap its own gate in a span.
  - `emit/1` (this module) -- the Scoria-internal producer, and the one
    G1..G4 call. It is a PURE EMITTER, not a wrapper: it takes an
    already-completed evaluation and emits its span. This is the right
    shape because Scoria's four gates do not have a wrappable closure at
    their decision point -- `ReleaseGate.check/1` runs inline in the caller
    and returns a tagged tuple; the workflow gates fire inside a
    multi-branch `case` on an outcome that has already been computed. A
    wrapper would require restructuring four live call sites to invert
    their control flow for no gain. `emit/1` mirrors
    `Scoria.Observe.emit_retriever_span/1`'s existing shape (a
    caller-supplied `started_wall`, a caller-supplied outcome) and costs
    ~3 lines at each call site.
  """

  alias Scoria.Observe
  alias Scoria.Observe.Semconv
  alias Scoria.Observe.SpanKind

  @doc """
  Emits one GUARDRAIL-kind span for an already-completed guardrail
  evaluation (D-05c). Always returns `:ok`.

  `input` is a map with:
  - `:name` -- one of `Semconv.guardrail_names/0`
  - `:decision` -- one of `Semconv.guardrail_decisions/0`
  - `:reason_code` -- an atom or binary, run through
    `Semconv.normalize_reason_code/1`. Omitted/`nil` is a no-op (the allow
    decision carries no reason code).
  - `:subject_ref`, `:policy_key` -- optional ids
  - `:trace_id`, `:parent_id`, `:tenant_id`, `:workflow_run_id`,
    `:session_id`, `:span_id` (own-id semantics -- a fresh id is minted
    when omitted)
  - `:started_wall` (a `DateTime`) and `:start_mono` (a
    `System.monotonic_time/0` reading) -- the duration pair. The span is
    "it ran", and how long it took is the point (D-05c).

  **The span shape:**
  - `span_kind` = `SpanKind.normalize("guardrail")`;
    `attributes[Semconv.openinference_span_kind_key()]` = `"GUARDRAIL"`.
  - `name` = `"guardrail." <> gate_name` (e.g. `"guardrail.release_gate"`)
    -- at most 4 distinct values, low-cardinality by construction.
  - `status_code` is ALWAYS `"OK"` -- a block is NOT a span error (D-05e):
    the evaluation succeeded; the business decision went a particular way.
    Never derived from the decision -- that would light every blocked run
    red in the trace tree and feed junk into the `"ERROR"`-status
    negative-signal sampler at `online_scoring.ex:453`. The decision lives
    in the `decision` attribute, and nowhere else.
  - Attributes built by `Semconv.guardrail_attributes/1` from an explicit,
    caller-input-independent five-field map -- `input`'s extra keys (a
    `reason:`, an `explanation:`, anything else) are never read, so a
    free-text key cannot reach the span (D-05g, SEC-01's sharpest rule).
  - `tenant_id`/`workflow_run_id`/`session_id` written BOTH top-level and
    into attributes, mirroring `Scoria.Observe`'s shared span-map builder
    (D-00c/D-01e).

  Emits on `[:scoria, :observe, :span, :stop]`, wrapped `try/rescue -> :ok`
  end to end -- a malformed `input` or a raising telemetry handler can
  never propagate into the caller's run lifecycle (T-53-12). Observability
  never breaks host business logic.
  """
  @spec emit(map()) :: :ok
  def emit(input) when is_map(input) do
    do_emit(input)
  rescue
    _ -> :ok
  end

  defp do_emit(input) do
    gate_name = Map.get(input, :name)
    span_name = "guardrail." <> to_string(gate_name)

    guardrail_fields = %{
      name: gate_name,
      decision: Map.get(input, :decision),
      reason_code: normalize_reason_code(Map.get(input, :reason_code)),
      subject_ref: Map.get(input, :subject_ref),
      policy_key: Map.get(input, :policy_key)
    }

    normalized_kind = SpanKind.normalize("guardrail")

    attributes =
      Semconv.guardrail_attributes(guardrail_fields)
      |> Map.put(
        Semconv.openinference_span_kind_key(),
        SpanKind.to_openinference(normalized_kind)
      )
      |> merge_scoped_ids(input)

    start_wall = Map.get(input, :started_wall) || DateTime.utc_now()
    end_time = monotonic_end_time(start_wall, Map.get(input, :start_mono))
    span_id = Map.get(input, :span_id) || Ecto.UUID.generate()

    span = %{
      name: span_name,
      span_kind: normalized_kind,
      status_code: "OK",
      start_time: start_wall,
      end_time: end_time,
      trace_id: Map.get(input, :trace_id),
      id: span_id,
      parent_id: Map.get(input, :parent_id),
      tenant_id: Map.get(input, :tenant_id),
      workflow_run_id: Map.get(input, :workflow_run_id),
      session_id: Map.get(input, :session_id),
      attributes: attributes
    }

    emit_span(span)

    maybe_emit_guardrail_triggered(span_id, end_time, guardrail_fields)
  end

  # `guardrail_triggered` is reserved for an actual intervention (D-04a) --
  # the span already records `allow` durably, so a caller correctly
  # allowing a step (or omitting a decision entirely) is deliberately NOT
  # a point event. `nil` decision only occurs for a malformed/incomplete
  # caller input and stays silent here too.
  defp maybe_emit_guardrail_triggered(_span_id, _time, %{decision: decision})
       when decision in [nil, "allow"],
       do: :ok

  defp maybe_emit_guardrail_triggered(span_id, time, guardrail_fields) do
    Observe.emit_event(%{
      name: :guardrail_triggered,
      span_id: span_id,
      time: time,
      attributes:
        Semconv.guardrail_attributes(%{
          name: guardrail_fields.name,
          decision: guardrail_fields.decision,
          reason_code: guardrail_fields.reason_code
        })
    })

    :ok
  end

  # `nil` reason_code (the `allow` decision) is a no-op -- do not run it
  # through the fallback path, which would spuriously log + emit
  # `[:scoria, :observe, :guardrail, :fallback]` for a caller that
  # correctly omitted a reason code.
  defp normalize_reason_code(nil), do: nil
  defp normalize_reason_code(value), do: Semconv.normalize_reason_code(value)

  # Mirrors `Scoria.Observe`'s shared span-map builder's scoped-id
  # double-write (D-00c) -- a top-level span-map field AND an `attributes`
  # entry, each written only when present.
  defp merge_scoped_ids(attributes, input) do
    attributes
    |> maybe_put_scoped_id("tenant_id", Map.get(input, :tenant_id))
    |> maybe_put_scoped_id("workflow_run_id", Map.get(input, :workflow_run_id))
    |> maybe_put_scoped_id("session_id", Map.get(input, :session_id))
  end

  defp maybe_put_scoped_id(attributes, _key, nil), do: attributes
  defp maybe_put_scoped_id(attributes, key, value), do: Map.put(attributes, key, value)

  # Mirrors `Scoria.Observe`'s `monotonic_end_time/2`: `end_time` derived
  # from the monotonic clock rather than two back-to-back wall reads, so a
  # real elapsed interval is provable (`max(elapsed_us, 1)` guarantees
  # strictly-after even for a near-instant evaluation). A missing
  # `start_mono` degrades to a zero-width span rather than raising -- the
  # caller-supplied duration pair is optional context, not a hard
  # requirement of a valid emission.
  defp monotonic_end_time(start_wall, nil), do: start_wall

  defp monotonic_end_time(start_wall, start_mono) do
    elapsed_native = System.monotonic_time() - start_mono
    elapsed_us = System.convert_time_unit(elapsed_native, :native, :microsecond)
    DateTime.add(start_wall, max(elapsed_us, 1), :microsecond)
  end

  defp emit_span(span) do
    :telemetry.execute([:scoria, :observe, :span, :stop], %{}, span)
    :ok
  rescue
    _ -> :ok
  end
end
